github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: prebuild
    init: |
      curl -L --http1.1 https://cnfl.io/ccloud-cli | sudo sh -s -- -b /usr/local/bin
      mvn clean package
      exit

  - name: create properties
    before: |
      cat<<-EOF>ccloud.properties
        # Required connection configs for Kafka producer, consumer, and admin
        bootstrap.servers=$CCLOUD_BOOTSTRAP_SERVER
        security.protocol=SASL_SSL
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='$CCLOUD_API_KEY'   password='$CCLOUD_API_SECRET';
        sasl.mechanism=PLAIN
        # Required for correctness in Apache Kafka clients prior to 2.6
        client.dns.lookup=use_all_dns_ips

        # Best practice for Kafka producer to prevent data loss
        acks=all

        # Required connection configs for Confluent Cloud Schema Registry
        schema.registry.url=$CCLOUD_SR_URL
        basic.auth.credentials.source=USER_INFO
        basic.auth.user.info=$CCLOUD_SR_API_KEY:$CCLOUD_SR_API_SECRET
        EOF


  - name: producer
    command: mvn exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ProducerExample" -Dexec.args="./ccloud.properties test1"

  - name: consumer
    command: mvn exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ConsumerExample" -Dexec.args="./ccloud.properties test1"

  - name: cp-demo
    command: |
      if [ -z "$DISABLE_AUTOSTART" ]; then
        echo "🚀 Starting up cp-demo (you can disable autostart by exporting DISABLE_AUTOSTART environment variable, see https://www.gitpod.io/docs/environment-variables)"
        ./scripts/start.sh
        echo "🚀 You can now follow steps in https://docs.confluent.io/platform/current/tutorials/cp-demo/docs/on-prem.html#guided-tutorial"
      else
        echo "ℹ️ DISABLE_AUTOSTART environment variable is set, use ./scripts/start.sh to start cp-demo"
      fi
      gp sync-done cp-demo

  - name: hybrid cloud
    command: |
      gp sync-await cp-demo
      ./scripts/create-ccloud-workflow.sh
      sleep 3000 # Let demo run for 50 minutes before tearing down ccloud environment
      source ./ccloud_library.sh
      source delta_configs/env.delta
      ccloud::destroy_ccloud_stack $SERVICE_ACCOUNT_ID
