github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

tasks:
  - name: prebuild
    init: |
      curl -L --http1.1 https://cnfl.io/ccloud-cli | sudo sh -s -- -b /usr/local/bin
      mvn clean package

  - name: launch
    before: |
      cat<<-EOF>ccloud.properties
      # Required connection configs for Kafka producer, consumer, and admin
      bootstrap.servers=$CCLOUD_BOOTSTRAP_SERVER
      security.protocol=SASL_SSL
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='$CCLOUD_API_KEY'   password='$CCLOUD_API_SECRET';
      sasl.mechanism=PLAIN
      # Required for correctness in Apache Kafka clients prior to 2.6
      client.dns.lookup=use_all_dns_ips

      # Best practice for Kafka producer to prevent data loss
      acks=all

      # Required connection configs for Confluent Cloud Schema Registry
      schema.registry.url=$CCLOUD_SR_URL
      basic.auth.credentials.source=USER_INFO
      basic.auth.user.info=$CCLOUD_SR_API_KEY:$CCLOUD_SR_API_SECRET
      EOF
      ccloud login --save


  - name: producer
    command: mvn exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ProducerExample" -Dexec.args="./ccloud.properties test1"

  - name: consumer
    command: mvn exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ConsumerExample" -Dexec.args="./ccloud.properties test1"

vscode:
  extensions:
    - vscjava.vscode-java-pack